function daysAgo(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

export const MOCK_LEADS = [
  {
    id: 1,
    name: 'Sarah Kim',
    email: 'skim@urbanedge.com',
    company: 'UrbanEdge Apartments',
    property_address: '1200 S Congress Ave',
    city: 'Austin', state: 'TX',
    score: 87, tier: 'Hot',
    scoreBreakdown: {
      marketSize:    { score: 25, max: 25, label: 'Market Size' },
      rentalDemand:  { score: 21, max: 25, label: 'Rental Demand' },
      economicHealth:{ score: 20, max: 25, label: 'Economic Health' },
      marketScale:   { score: 21, max: 25, label: 'Market Scale' },
    },
    population: 1289054, median_income: 92731, renter_pct: 52.9,
    median_rent: 1561, total_housing_units: 571625, unemployment_rate: 4.3,
    emailDraft: {
      subject: 'Quick thought on leasing efficiency for UrbanEdge in Austin',
      body: `Hi Sarah,\n\nI was looking into the Austin market and UrbanEdge Apartments — it's clear what a dynamic city you're in. With over half of Austin's households (52.9%) renting and median rents around $1,561/mo, the volume of leasing inquiries your team fields must be substantial.\n\nMany properties in similar markets struggle to keep up with after-hours inquiry volume, missing leads they never even knew existed. At EliseAI, we automate those first-touch leasing conversations — inquiries, tour scheduling, follow-ups — with a 60-second response time around the clock, saving agents 20+ hours per week.\n\nWould you be open to a 20-minute call this week to see how this could work for UrbanEdge?\n\n[Your Name] | EliseAI`,
    },
    insights: [
      'Strong Fit: Austin\'s 52.9% renter-occupied rate signals extremely high leasing volume — ideal for automation ROI.',
      'Strong Fit: $1,561 median rent means each captured lease carries significant revenue impact.',
      'Strong Fit: Population of 1.29M with major tech employers driving sustained in-migration and renter demand.',
      'Neutral: 4.3% TX unemployment is slightly above national avg — Austin\'s job market remains strong regardless.',
      'Hot (87/100): Top-tier lead. Prioritize for immediate outreach this week.',
    ],
    processed_at: daysAgo(2), status: 'processed',
  },
  {
    id: 2,
    name: 'Marcus Thompson',
    email: 'mthompson@sunbelt-residential.com',
    company: 'Sunbelt Residential',
    property_address: '4521 Pecos St',
    city: 'Denver', state: 'CO',
    score: 82, tier: 'Hot',
    scoreBreakdown: {
      marketSize:    { score: 21, max: 25, label: 'Market Size' },
      rentalDemand:  { score: 21, max: 25, label: 'Rental Demand' },
      economicHealth:{ score: 19, max: 25, label: 'Economic Health' },
      marketScale:   { score: 21, max: 25, label: 'Market Scale' },
    },
    population: 968058, median_income: 87042, renter_pct: 50.1,
    median_rent: 1478, total_housing_units: 432000, unemployment_rate: 3.8,
    emailDraft: {
      subject: 'Scaling leasing ops at Sunbelt Residential — Denver\'s growing fast',
      body: `Hi Marcus,\n\nDenver's multifamily market is one of the most active in the Mountain West. With 50% of households renting and median rents at $1,478/mo, the leasing volume Sunbelt Residential handles must be significant.\n\nAt EliseAI, we help multi-property operators automate the full leasing conversation workflow — inquiries, tour confirmations, follow-ups — so your team focuses on closing, not fielding calls. Our platform handles multi-property setups natively, which tends to be a game-changer for teams scaling across regions.\n\nWorth a 20-minute look this week?\n\n[Your Name] | EliseAI`,
    },
    insights: [
      'Strong Fit: 50.1% renter-occupied + 432K housing units = massive addressable portfolio in Denver county alone.',
      'Strong Fit: "Sunbelt Residential" name suggests multi-market presence — potential enterprise deal, not just a single property.',
      'Strong Fit: $87K median income signals premium renter quality — premium operators are top EliseAI targets.',
      'Strong Fit: 3.8% CO unemployment is healthy — stable tenant base reduces turnover and churn risk.',
      'Hot (82/100): Second-highest scoring lead. Prioritize alongside Austin for this week\'s outreach.',
    ],
    processed_at: daysAgo(5), status: 'processed',
  },
  {
    id: 3,
    name: 'Robert Chen',
    email: 'rchen@keystonepm.com',
    company: 'Keystone Property Management',
    property_address: '350 N 1st Ave',
    city: 'Phoenix', state: 'AZ',
    score: 71, tier: 'Warm',
    scoreBreakdown: {
      marketSize:    { score: 25, max: 25, label: 'Market Size' },
      rentalDemand:  { score: 12, max: 25, label: 'Rental Demand' },
      economicHealth:{ score: 17, max: 25, label: 'Economic Health' },
      marketScale:   { score: 17, max: 25, label: 'Market Scale' },
    },
    population: 1608139, median_income: 61094, renter_pct: 40.8,
    median_rent: 1241, total_housing_units: 729000, unemployment_rate: 4.2,
    emailDraft: {
      subject: 'Handling Phoenix\'s new supply surge at Keystone PM',
      body: `Hi Robert,\n\nPhoenix added over 11,000 multifamily units last year — the largest supply increase in the metro's history. For a PM firm like Keystone, that means managing new lease-ups while your competitors are absorbing demand.\n\nAt EliseAI, we've helped PM firms in high-supply markets like Phoenix cut lead response time from 4+ hours to 60 seconds, directly lifting occupancy during competitive lease-up periods.\n\nWould it make sense to connect for 20 minutes to see if this fits Keystone's current challenges?\n\n[Your Name] | EliseAI`,
    },
    insights: [
      'Good Fit: Phoenix is the largest housing market in AZ by volume (729K units) — massive absolute scale even at lower renter %.',
      'Moderate Fit: 40.8% renter-occupied is below target threshold (45%+) — Phoenix skews more owner-occupied than comparable metros.',
      'Opportunity: High new supply creates lease-up pressure — EliseAI\'s speed-to-lead value prop is most compelling in supply-heavy markets.',
      'Watch: $61K median income is lower than Austin/Denver comps — may indicate a more price-sensitive tenant base.',
      'Warm (71/100): Strong on scale, weaker on rental density. Good discovery call candidate, lower urgency than Hot leads.',
    ],
    processed_at: daysAgo(8), status: 'processed',
  },
  {
    id: 4,
    name: 'Jennifer Davis',
    email: 'jdavis@carolina-living.com',
    company: 'Carolina Living Properties',
    property_address: '2100 Park Rd',
    city: 'Charlotte', state: 'NC',
    score: 64, tier: 'Warm',
    scoreBreakdown: {
      marketSize:    { score: 17, max: 25, label: 'Market Size' },
      rentalDemand:  { score: 12, max: 25, label: 'Rental Demand' },
      economicHealth:{ score: 18, max: 25, label: 'Economic Health' },
      marketScale:   { score: 17, max: 25, label: 'Market Scale' },
    },
    population: 874579, median_income: 62817, renter_pct: 40.2,
    median_rent: 1189, total_housing_units: 375000, unemployment_rate: 3.8,
    emailDraft: {
      subject: 'Leasing automation for Carolina Living — Charlotte\'s growing fast',
      body: `Hi Jennifer,\n\nCharlotte's multifamily market has had a strong run — consistent in-migration and a booming financial services sector are keeping rental demand steady even as new supply comes online.\n\nFor a regional operator like Carolina Living, managing leasing inquiries across multiple NC properties can get complex. At EliseAI, we help property management teams automate first-response leasing communications so every inquiry gets answered instantly — regardless of time of day or how many properties you're managing.\n\nHappy to show you a quick 20-minute demo focused on Charlotte-area use cases?\n\n[Your Name] | EliseAI`,
    },
    insights: [
      'Moderate Fit: Charlotte is a growing Southeast market (874K pop) but renter % (40.2%) is below the 45%+ ideal threshold.',
      'Positive Signal: 3.8% NC unemployment and $62.8K median income suggest a stable, growing tenant base.',
      'Regional Opportunity: "Carolina Living" suggests multi-property NC presence — ask about total unit count on the call.',
      'Lower Urgency: Score of 64 places this in Warm tier — good for nurture sequence, not top-of-queue outreach.',
      'Competitive Note: Charlotte is attracting more proptech attention — moving early could establish a relationship before competitors get in.',
    ],
    processed_at: daysAgo(18), status: 'processed',
  },
  {
    id: 5,
    name: 'Michael Okonkwo',
    email: 'mokonkwo@lakeside-apts.com',
    company: 'Lakeside Apartments',
    property_address: '8500 Horner Blvd',
    city: 'Fayetteville', state: 'NC',
    score: 38, tier: 'Pass',
    scoreBreakdown: {
      marketSize:    { score: 7,  max: 25, label: 'Market Size' },
      rentalDemand:  { score: 8,  max: 25, label: 'Rental Demand' },
      economicHealth:{ score: 9,  max: 25, label: 'Economic Health' },
      marketScale:   { score: 7,  max: 25, label: 'Market Scale' },
    },
    population: 208501, median_income: 44231, renter_pct: 43.1,
    median_rent: 921, total_housing_units: 89000, unemployment_rate: 6.8,
    emailDraft: {
      subject: 'Improving resident communications at Lakeside Apartments',
      body: `Hi Michael,\n\nI came across Lakeside Apartments and wanted to reach out. With Fayetteville's rental market showing some softness, I imagine keeping occupancy levels up is a priority.\n\nOne area where smaller operators often capture quick wins is response time. EliseAI ensures every leasing inquiry gets a personalized response within 60 seconds — even on weekends and after hours when most inquiries go unanswered.\n\nWould it make sense to connect briefly and see if this fits Lakeside's current situation?\n\n[Your Name] | EliseAI`,
    },
    insights: [
      'Low Fit: Fayetteville is a military/secondary market (pop 208K) — limited growth trajectory vs. target metros.',
      'Concern: 6.8% NC unemployment is significantly above state average — economic fragility in this market.',
      'Low Value: $921 median rent and $44K median income suggest limited budget for tech investment.',
      'Smaller Portfolio: Single property address implies small operator — lower ACV potential for EliseAI.',
      'Pass (38/100): Below qualification threshold. Route to low-priority nurture or exclude from active outreach.',
    ],
    processed_at: daysAgo(32), status: 'processed',
  },
  {
    id: 6,
    name: 'Amanda Torres',
    email: 'atorres@westgate-pm.com',
    company: 'Westgate Property Management',
    property_address: '500 Brickell Ave',
    city: 'Miami', state: 'FL',
    score: null, tier: null, scoreBreakdown: null,
    population: null, median_income: null, renter_pct: null,
    median_rent: null, total_housing_units: null, unemployment_rate: null,
    emailDraft: null, insights: [],
    processed_at: null, status: 'pending',
  },
]
